service: event-bridge-publisher
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/posts"
    - Effect: Allow
      Action:
        - events:PutEvents
      Resource:
        - "*"

functions:
  getPosts:
    handler: handler.getPosts
    events:
      - http:
          path: post/{user_id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                user_id: true
