service: event-bridge-listener
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/posts"

functions:
  getPosts:
    handler: handler.getPosts
    events:
      - eventBridge:
          pattern:
            source:
              - acme.newsletter.campaign  
